CXX = clang++ -m32
CXXFLAGS = -Wall -g
OFILES = TreeNode.o BinarySearchTree.o BinarySearchTreeTest.o

.SUFFIXES: .o .cpp

main: $(OFILES)
	  $(CXX) $(CXXFLAGS) $(OFILES)

clean:
	  /bin/rm -f *.o *~ a.out

